# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cloudalphatest

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - uses: azure/docker-login@v1
      with:
        login-server: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_91a7557fdfca4085b1f93f0fcdcdc848 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7e7c13aae49d4f239e40294b7bb0479d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2.2.1
      with:
        push: true
        tags: appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cloudalphatest'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_180f9e43e5994bbbb3610ba0d39dac6b }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_91a7557fdfca4085b1f93f0fcdcdc848 }}/appsvc/staticsite:${{ github.sha }}'